### ISSUE TITLE
Problems with using the wrapper.

### ISSUE THREAD

**Issue by roskoN** [clips/topbox#1]
Hi,

First of all, thank you very much for sharing this with the community!

Unfortunately, when I follow your instructions and I run the provided example, I get a java exception. When I run the examples provided on STMT's website, there seem to be no problems. Can you please have a look into? Thank you very much!

I am using Ubuntu 16.04.01 and my java is:
java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

Here is the exception text I get: 

`(topbox) rosko@rosko-ThinkPad-W510:~/GIT$ python ./test1.py 
[cell] creating /home/rosko/GIT/topbox/box/test_model_train.csv.term-counts.cache.16e042a9.gz
[cell] creating /home/rosko/GIT/topbox/box/test_model_train.csv.term-counts.cache.ade3ddc9.gz
[Train] iteration 0
edu.stanford.nlp.tmt.data.concurrent.ConcurrentException: edu.stanford.nlp.tmt.data.concurrent.ConcurrentException: edu.stanford.nlp.tmt.data.concurrent.ConcurrentException: java.lang.ArrayIndexOutOfBoundsException: 0
	at edu.stanford.nlp.tmt.data.concurrent.Concurrent$InnerNode$2.value(Concurrent.scala:185)
	at edu.stanford.nlp.tmt.data.concurrent.Concurrent$.reduce(Concurrent.scala:205)
	at edu.stanford.nlp.tmt.learn.ThreadedModeler.learnIteration(ThreadedModeler.scala:116)
	at edu.stanford.nlp.tmt.learn.Modeler$$anonfun$train$1.apply(Modeler.scala:114)
	at edu.stanford.nlp.tmt.learn.Modeler$$anonfun$train$1.apply(Modeler.scala:114)
	at edu.stanford.nlp.tmt.learn.Train$.apply(Train.scala:184)
	at edu.stanford.nlp.tmt.learn.Modeler$class.train(Modeler.scala:113)
	at edu.stanford.nlp.tmt.learn.ThreadedModeler.train(ThreadedModeler.scala:35)
	at edu.stanford.nlp.tmt.stage.package$.TrainCVB0LabeledLDA(package.scala:83)
	at Main$$anon$1.<init>(test_model_train.scala:51)
	at Main$.main(test_model_train.scala:1)
	at Main.main(test_model_train.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:78)
	at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:24)
	at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:88)
	at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:78)
	at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:33)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:40)
	at scala.tools.nsc.ScriptRunner.scala$tools$nsc$ScriptRunner$$runCompiled(ScriptRunner.scala:171)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:188)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:188)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply$mcZ$sp(ScriptRunner.scala:157)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:131)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:131)
	at scala.tools.nsc.util.package$.waitingForThreads(package.scala:26)
	at scala.tools.nsc.ScriptRunner.withCompiledScript(ScriptRunner.scala:130)
	at scala.tools.nsc.ScriptRunner.runScript(ScriptRunner.scala:188)
	at scala.tools.nsc.ScriptRunner.runScriptAndCatch(ScriptRunner.scala:201)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:58)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:80)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:89)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at edu.stanford.nlp.tmt.TMTMain$.main(TMTMain.scala:57)
	at edu.stanford.nlp.tmt.TMTMain.main(TMTMain.scala)
Caused by: edu.stanford.nlp.tmt.data.concurrent.ConcurrentException: edu.stanford.nlp.tmt.data.concurrent.ConcurrentException: java.lang.ArrayIndexOutOfBoundsException: 0
	at edu.stanford.nlp.tmt.data.concurrent.Concurrent$InnerNode$2.value(Concurrent.scala:185)
	at edu.stanford.nlp.tmt.data.concurrent.Concurrent$InnerNode$2$$anon$6.run(Concurrent.scala:172)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: edu.stanford.nlp.tmt.data.concurrent.ConcurrentException: java.lang.ArrayIndexOutOfBoundsException: 0
	... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at edu.stanford.nlp.tmt.model.SoftAssignmentModelState.numTerms(SoftAssignments.scala:44)
	at edu.stanford.nlp.tmt.model.llda.CVB0LabeledLDA$.doCollect(CVB0LabeledLDA.scala:309)
	at edu.stanford.nlp.tmt.model.llda.CVB0LabeledLDA$.doCollect(CVB0LabeledLDA.scala:285)
	at edu.stanford.nlp.tmt.learn.ThreadedModeler$$anonfun$3.apply(ThreadedModeler.scala:116)
	... 4 more
Loading /home/rosko/GIT/topbox/box/test_model_train
java.io.FileNotFoundException: /home/rosko/GIT/topbox/box/test_model_train/params.txt (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:120)
	at scalanlp.io.FileStreams$.input(FileStreams.scala:40)
	at scalanlp.serialization.GenericFileSerializationFromText$$anon$2.read(FileSerialization.scala:101)
	at scalanlp.serialization.GenericFileSerializationFromText$$anon$2.read(FileSerialization.scala:97)
	at scalanlp.serialization.SerializationFormat$class.read(Serialization.scala:84)
	at scalanlp.serialization.FileSerialization$.read(FileSerialization.scala:40)
	at scalanlp.serialization.FileSerialization$.readText(FileSerialization.scala:46)
	at edu.stanford.nlp.tmt.model.llda.LabeledLDAModelParams$FileReadWritable$.read(LabeledLDA.scala:106)
	at edu.stanford.nlp.tmt.model.llda.LabeledLDAModelParams$FileReadWritable$.read(LabeledLDA.scala:104)
	at scalanlp.serialization.SerializationFormat$class.read(Serialization.scala:84)
	at scalanlp.serialization.FileSerialization$.read(FileSerialization.scala:40)
	at edu.stanford.nlp.tmt.learn.SerializableModelCompanion$class.load(ModelCompanion.scala:128)
	at edu.stanford.nlp.tmt.model.llda.CVB0LabeledLDA$.load(CVB0LabeledLDA.scala:285)
	at edu.stanford.nlp.tmt.stage.package$.LoadCVB0LabeledLDA(package.scala:140)
	at Main$$anon$1.<init>(test_model_test.scala:14)
	at Main$.main(test_model_test.scala:1)
	at Main.main(test_model_test.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:78)
	at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:24)
	at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:88)
	at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:78)
	at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:33)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:40)
	at scala.tools.nsc.ScriptRunner.scala$tools$nsc$ScriptRunner$$runCompiled(ScriptRunner.scala:171)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:188)
	at scala.tools.nsc.ScriptRunner$$anonfun$runScript$1.apply(ScriptRunner.scala:188)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply$mcZ$sp(ScriptRunner.scala:157)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:131)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:131)
	at scala.tools.nsc.util.package$.waitingForThreads(package.scala:26)
	at scala.tools.nsc.ScriptRunner.withCompiledScript(ScriptRunner.scala:130)
	at scala.tools.nsc.ScriptRunner.runScript(ScriptRunner.scala:188)
	at scala.tools.nsc.ScriptRunner.runScriptAndCatch(ScriptRunner.scala:201)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:58)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:80)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:89)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at edu.stanford.nlp.tmt.TMTMain$.main(TMTMain.scala:57)
	at edu.stanford.nlp.tmt.TMTMain.main(TMTMain.scala)
Traceback (most recent call last):
  File "./test1.py", line 21, in <module>
    y_true, y_score = stmt.results(test_labels, array=True)
  File "/home/rosko/GIT/topbox/stmt.py", line 342, in results
    'train', LIDX), 'r')
IOError: [Errno 2] No such file or directory: '/home/rosko/GIT/topbox/box/test_model_/train00000/label-index.txt`

**Comment by cmry** [comment]
Hey @roskoN, thank you very much for reporting this. 8b5a1ae0980a7c6ab1352ba9aa382a543a4ced74 should fix it! Note I also changed the `train.scala`, in `box` for the examples to work, so if you would like to try different parameters you might wanna change those up. Please let me know if things are in order now.

**Comment by roskoN** [comment]
Hi @cmry,

I just run your examples and everything seems to be fine. Thank you very much for the swift response!
