### ISSUE TITLE
Error while running the example.

### ISSUE THREAD

**Issue by rpanchal1996** [clips/topbox#8]
I was setting up topbox and was trying to run the example script provided when the following error occured:
```
Traceback (most recent call last):
  File "/home/rudresh/Documents/clips/clips-repo/topbox/stmt.py", line 178, in regex
    rf = open(wf, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rudresh/Documents/clips/clips-repo/topbox/boxbit_of_testing_train.scala'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "somescript.py", line 9, in <module>
    stmt.train(space, labels)
  File "/home/rudresh/Documents/clips/clips-repo/topbox/stmt.py", line 438, in train
    self.run(space, labels, 'train')
  File "/home/rudresh/Documents/clips/clips-repo/topbox/stmt.py", line 420, in run
    self.boot(step)
  File "/home/rudresh/Documents/clips/clips-repo/topbox/stmt.py", line 120, in boot
    self.scala(mod)
  File "/home/rudresh/Documents/clips/clips-repo/topbox/stmt.py", line 205, in scala
    self.regex(f, o_csv, n_csv) if not r else self.regex(f, n_csv, o_csv)
  File "/home/rudresh/Documents/clips/clips-repo/topbox/stmt.py", line 180, in regex
    rf = open(f, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/rudresh/Documents/clips/clips-repo/topbox/boxtrain.scala'
```

I think the root of the problem is the `self.dir` variable in the initializer/constructor in `stmt.py` on line 101-102. 

I replaced 
```
self.dir = path.normpath(path.dirname(path.realpath(__file__)) + \
            '{0}box{0}'.format(sep))
```
with 
```
 self.dir = path.normpath(path.dirname(path.realpath(__file__)) + \
            '{0}box{0}'.format(sep)) +'/'
```
and it fixed the problem. Is this something that only I am facing? Is there something that I am missing out?
This is on Ubuntu 16.04 running Python 3.5.2.

**Comment by cmry** [comment]
Thanks, normpath apparently removes the trailing slash in `{0}box{0}`. Added it a few days ago for Windows compatibility and haven't tested yet. Thanks!
